### ISSUE TITLE
Loot Table Error

### ISSUE THREAD

**Issue by WenXin20** [minecraftabnormals/The-Endergetic-Expansion#29]
`Minecraft v1.15.2`
`Endergetic v1.2.5`

The log prints out the following error for Frisbloom Seeds from the Frisbloom Stem:

```
[03Apr2020 23:08:10.067] [Server thread/ERROR] [net.minecraft.world.storage.loot.LootTableManager/]: Couldn't parse loot table endergetic:blocks/frisbloom_seeds
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'endergetic:frisbloom_seeds'
	at net.minecraft.util.JSONUtils.func_219793_a(SourceFile:128) ~[?:?]
	at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.util.JSONUtils.func_188172_b(SourceFile:128) ~[?:?]
	at net.minecraft.util.JSONUtils.func_188180_i(SourceFile:136) ~[?:?]
	at net.minecraft.world.storage.loot.ItemLootEntry$Serializer.func_212829_b_(SourceFile:54) ~[?:?]
	at net.minecraft.world.storage.loot.ItemLootEntry$Serializer.func_212829_b_(SourceFile:35) ~[?:?]
	at net.minecraft.world.storage.loot.StandaloneLootEntry$Serializer.func_212865_b_(SourceFile:156) ~[?:?]
	at net.minecraft.world.storage.loot.StandaloneLootEntry$Serializer.func_212865_b_(SourceFile:130) ~[?:?]
	at net.minecraft.world.storage.loot.LootEntryManager$Serializer.deserialize(SourceFile:53) ~[?:?]
	at net.minecraft.world.storage.loot.LootEntryManager$Serializer.deserialize(SourceFile:41) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.15.2-extra.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server-1.15.2-extra.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[server-1.15.2-extra.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.15.2-extra.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.15.2-extra.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[server-1.15.2-extra.jar:?]
	at net.minecraft.util.JSONUtils.func_188179_a(SourceFile:441) ~[?:?]
	at net.minecraft.util.JSONUtils.func_188174_a(SourceFile:449) ~[?:?]
	at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:205) ~[?:?]
	at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:202) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.15.2-extra.jar:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server-1.15.2-extra.jar:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[server-1.15.2-extra.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.15.2-extra.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.15.2-extra.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[server-1.15.2-extra.jar:?]
	at net.minecraft.util.JSONUtils.func_188179_a(SourceFile:441) ~[?:?]
	at net.minecraft.util.JSONUtils.func_188177_a(SourceFile:457) ~[?:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:245) ~[?:?]
	at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:242) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server-1.15.2-extra.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[server-1.15.2-extra.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[server-1.15.2-extra.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[server-1.15.2-extra.jar:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:824) ~[?:?]
	at net.minecraft.world.storage.loot.LootTableManager.lambda$apply$0(LootTableManager.java:47) ~[?:?]
	at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.world.storage.loot.LootTableManager.func_212853_a_(LootTableManager.java:44) ~[?:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_212853_a_(LootTableManager.java:22) ~[?:?]
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_231]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_231]
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_195568_a(MinecraftServer.java:1464) [?:?]
	at net.minecraft.server.MinecraftServer.func_195560_a(MinecraftServer.java:450) [?:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:363) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:212) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[03Apr2020 23:08:13.990] [Server thread/ERROR] [net.minecraft.world.storage.loot.LootTableManager/]: Couldn't parse loot table endergetic:blocks/frisbloom_stem
```

**Comment by SmellyModder** [comment]
Luckily this won't affect anything in the mod or in other mods. It's just a log error from a missing item and block, it's been fixed in dev recently by ea4d8b2

**Comment by SmellyModder** [comment]
New curseforge release build that fixes this

**Comment by Gringo1337** [comment]
How did you fix this? I have the same problem
